name: Python uppercase

on:
  push: 
    paths:
      - "py-upper/**"
      - ".github/workflows/python-uppercase.yaml"
  workflow_dispatch:

jobs:
  tests:
    runs-on: self-hosted
    steps:
      - name: Display variables
        run: |
          echo "${{ runner.os }}"
      - name: Check python version
        run: python3 -V
      - name: Download application code
        uses: actions/checkout@v4
      - name: Configure cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{hashFiles('**/requirements.txt')}}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: List directory
        run: ls -lR
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Check python version
        run: python3 -V
      # - name: Install requirements
      #   run: pip install -r py-upper/requirements.txt
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "py-upper/requirements.txt"
      - name: Run tests
        run: pytest
        working-directory: py-upper
        
  build:
    
    runs-on: self-hosted
    strategy:
      matrix:
        python_version: ['3.12', '3.13']
    needs: tests
    steps:
      - name: Log python version
        run: echo "This run is for python ${{ matrix.python_version }}"
      - name: hostname
        run: hostname
      - name: Download application code
        uses: actions/checkout@v4
      - name: Configure cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{hashFiles('**/requirements.txt')}}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: List directory 1
        run: ls -lR
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Check python version
        run: python3 -V
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "py-upper/requirements.txt"
      
      - name: Compile
        run: pyinstaller --onefile uppercase.py
        working-directory: py-upper 
      
      - name: List directory 2
        run: ls -lR
        if: failure()
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "uppercase-software-${{ matrix.python_version }}"
          path: py-upper/dist/uppercase
          overwrite: true

  release:
    runs-on: self-hosted
    needs: build
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
      - name: List artifacts
        run: ls -lR artifacts
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
          body: "Binaries ready for download and run (on Ubuntu)"
          tag_name: ${ github.ref_name }