name: Variable Test - scopes
 
on:
  workflow_dispatch
 
env:
  DAY_OF_WEEK: Monday
 
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    outputs:
      TOMMORROW: ${{ steps.var_def.outputs.TOMMORROW }}
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        id: var_def
        run: |
          echo "$MYGREETING $First_Name. Today is $DAY_OF_WEEK!"
          echo "TODAY=PATEK" >> $GITHUB_ENV
          echo "TOMMORROW=SOBOTA" >> $GITHUB_OUTPUT
        env:
          First_Name: Mona
          MYGREETING: ${{ vars.GREETING }}
      - name: use var
        run: |
          echo "${{ env.TODAY }}}"
          echo "{{ steps.var_def.outputs.TOMMORROW}}"

  second_job:
    runs-on: ubuntu-latest
    needs: greeting_job
    steps:
      - name: "Display vars from previous job"
        run: |
          echo "TODAY: ${{ env.TODAY }}"
          echo "TOMMORROW: ${{ needs.greeting_job.outputs.TOMMORROW }}"
          echo "GREETING: ${{ vars.GREETING }}"
        env:
          GREETING: Hello